# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1490, 838)
        MainWindow.setStyleSheet("background-color: rgb(220, 175, 100);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_kamera = QtWidgets.QLabel(self.centralwidget)
        self.label_kamera.setGeometry(QtCore.QRect(440, 10, 1024, 768))
        self.label_kamera.setMinimumSize(QtCore.QSize(1024, 0))
        self.label_kamera.setMaximumSize(QtCore.QSize(1024, 16777215))
        self.label_kamera.setAutoFillBackground(False)
        self.label_kamera.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label_kamera.setText("")
        self.label_kamera.setObjectName("label_kamera")
        self.b_start_kamera = QtWidgets.QPushButton(self.centralwidget)
        self.b_start_kamera.setGeometry(QtCore.QRect(340, 710, 91, 23))
        self.b_start_kamera.setStyleSheet("background-color: rgb(160, 160, 160);")
        self.b_start_kamera.setObjectName("b_start_kamera")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 281, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.l_baglanti = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l_baglanti.setStyleSheet("color: rgb(255, 0, 0);\n"
"")
        self.l_baglanti.setObjectName("l_baglanti")
        self.gridLayout_2.addWidget(self.l_baglanti, 0, 2, 1, 1)
        self.b_baglan = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_baglan.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.b_baglan.setObjectName("b_baglan")
        self.gridLayout_2.addWidget(self.b_baglan, 0, 0, 1, 1)
        self.b_baglanti_kes = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_baglanti_kes.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.b_baglanti_kes.setObjectName("b_baglanti_kes")
        self.gridLayout_2.addWidget(self.b_baglanti_kes, 0, 1, 1, 1)
        self.b_armET = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_armET.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.b_armET.setObjectName("b_armET")
        self.gridLayout_2.addWidget(self.b_armET, 1, 0, 1, 1)
        self.b_disarmET = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b_disarmET.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.b_disarmET.setObjectName("b_disarmET")
        self.gridLayout_2.addWidget(self.b_disarmET, 1, 1, 1, 1)
        self.l_arm = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l_arm.setStyleSheet("color: rgb(255, 0, 0);\n"
"\n"
"")
        self.l_arm.setObjectName("l_arm")
        self.gridLayout_2.addWidget(self.l_arm, 1, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 150, 370, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.b_modLOITER = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_modLOITER.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.b_modLOITER.setObjectName("b_modLOITER")
        self.gridLayout_3.addWidget(self.b_modLOITER, 0, 2, 1, 1)
        self.b_modUYGULA = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_modUYGULA.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.b_modUYGULA.setObjectName("b_modUYGULA")
        self.gridLayout_3.addWidget(self.b_modUYGULA, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 0, 1, 1)
        self.b_modRTL = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_modRTL.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.b_modRTL.setObjectName("b_modRTL")
        self.gridLayout_3.addWidget(self.b_modRTL, 1, 2, 1, 1)
        self.b_modAUTO = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_modAUTO.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.b_modAUTO.setObjectName("b_modAUTO")
        self.gridLayout_3.addWidget(self.b_modAUTO, 1, 1, 1, 1)
        self.b_modFBWA = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.b_modFBWA.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.b_modFBWA.setObjectName("b_modFBWA")
        self.gridLayout_3.addWidget(self.b_modFBWA, 0, 1, 1, 1)
        self.l_mod = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.l_mod.setText("")
        self.l_mod.setObjectName("l_mod")
        self.gridLayout_3.addWidget(self.l_mod, 1, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 6, 141, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 141, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 250, 168, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.b_solalt = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.b_solalt.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.b_solalt.setObjectName("b_solalt")
        self.gridLayout.addWidget(self.b_solalt, 1, 0, 1, 1)
        self.b_solust = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.b_solust.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.b_solust.setObjectName("b_solust")
        self.gridLayout.addWidget(self.b_solust, 0, 0, 1, 1)
        self.b_sagust = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.b_sagust.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.b_sagust.setObjectName("b_sagust")
        self.gridLayout.addWidget(self.b_sagust, 0, 1, 1, 1)
        self.b_sagalt = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.b_sagalt.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.b_sagalt.setObjectName("b_sagalt")
        self.gridLayout.addWidget(self.b_sagalt, 1, 1, 1, 1)
        self.b_takipBaslat = QtWidgets.QPushButton(self.centralwidget)
        self.b_takipBaslat.setGeometry(QtCore.QRect(30, 340, 91, 23))
        self.b_takipBaslat.setStyleSheet("background-color: rgb(255, 136, 0);")
        self.b_takipBaslat.setObjectName("b_takipBaslat")
        self.b_takipDurdur = QtWidgets.QPushButton(self.centralwidget)
        self.b_takipDurdur.setGeometry(QtCore.QRect(130, 340, 91, 23))
        self.b_takipDurdur.setStyleSheet("background-color: rgb(255, 136, 0);")
        self.b_takipDurdur.setObjectName("b_takipDurdur")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 380, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 260, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 290, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 310, 91, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 340, 71, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(260, 360, 41, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(260, 390, 41, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(260, 410, 41, 31))
        self.label_10.setObjectName("label_10")
        self.l_alt = QtWidgets.QLabel(self.centralwidget)
        self.l_alt.setGeometry(QtCore.QRect(310, 260, 101, 16))
        self.l_alt.setText("")
        self.l_alt.setObjectName("l_alt")
        self.l_airspeed = QtWidgets.QLabel(self.centralwidget)
        self.l_airspeed.setGeometry(QtCore.QRect(310, 290, 111, 16))
        self.l_airspeed.setText("")
        self.l_airspeed.setObjectName("l_airspeed")
        self.l_groundspeed = QtWidgets.QLabel(self.centralwidget)
        self.l_groundspeed.setGeometry(QtCore.QRect(310, 320, 111, 16))
        self.l_groundspeed.setText("")
        self.l_groundspeed.setObjectName("l_groundspeed")
        self.l_battery = QtWidgets.QLabel(self.centralwidget)
        self.l_battery.setGeometry(QtCore.QRect(310, 340, 101, 21))
        self.l_battery.setText("")
        self.l_battery.setObjectName("l_battery")
        self.l_roll = QtWidgets.QLabel(self.centralwidget)
        self.l_roll.setGeometry(QtCore.QRect(310, 370, 101, 16))
        self.l_roll.setText("")
        self.l_roll.setObjectName("l_roll")
        self.l_pitch = QtWidgets.QLabel(self.centralwidget)
        self.l_pitch.setGeometry(QtCore.QRect(310, 390, 101, 21))
        self.l_pitch.setText("")
        self.l_pitch.setObjectName("l_pitch")
        self.l_yaw = QtWidgets.QLabel(self.centralwidget)
        self.l_yaw.setGeometry(QtCore.QRect(310, 412, 101, 21))
        self.l_yaw.setText("")
        self.l_yaw.setObjectName("l_yaw")
        self.l_kilitlenme = QtWidgets.QLabel(self.centralwidget)
        self.l_kilitlenme.setGeometry(QtCore.QRect(60, 500, 381, 151))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.l_kilitlenme.setFont(font)
        self.l_kilitlenme.setStyleSheet("color: rgb(204, 0, 0);")
        self.l_kilitlenme.setText("")
        self.l_kilitlenme.setObjectName("l_kilitlenme")
        self.b_stop_kamera = QtWidgets.QPushButton(self.centralwidget)
        self.b_stop_kamera.setGeometry(QtCore.QRect(340, 750, 91, 23))
        self.b_stop_kamera.setStyleSheet("background-color: rgb(160, 160, 160);")
        self.b_stop_kamera.setObjectName("b_stop_kamera")
        self.b_kamera_indir = QtWidgets.QPushButton(self.centralwidget)
        self.b_kamera_indir.setGeometry(QtCore.QRect(10, 690, 91, 23))
        self.b_kamera_indir.setObjectName("b_kamera_indir")
        self.b_kamera_kaldir = QtWidgets.QPushButton(self.centralwidget)
        self.b_kamera_kaldir.setGeometry(QtCore.QRect(110, 690, 101, 23))
        self.b_kamera_kaldir.setObjectName("b_kamera_kaldir")
        self.l_kamera_alt = QtWidgets.QLineEdit(self.centralwidget)
        self.l_kamera_alt.setGeometry(QtCore.QRect(20, 770, 61, 20))
        self.l_kamera_alt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.l_kamera_alt.setObjectName("l_kamera_alt")
        self.l_kamera_ust = QtWidgets.QLineEdit(self.centralwidget)
        self.l_kamera_ust.setGeometry(QtCore.QRect(120, 770, 61, 20))
        self.l_kamera_ust.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.l_kamera_ust.setObjectName("l_kamera_ust")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 720, 51, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(140, 720, 51, 31))
        self.label_12.setObjectName("label_12")
        self.b_arac_degistir = QtWidgets.QPushButton(self.centralwidget)
        self.b_arac_degistir.setGeometry(QtCore.QRect(30, 410, 121, 81))
        self.b_arac_degistir.setObjectName("b_arac_degistir")
        self.b_conf_ayarla = QtWidgets.QPushButton(self.centralwidget)
        self.b_conf_ayarla.setGeometry(QtCore.QRect(220, 690, 101, 23))
        self.b_conf_ayarla.setObjectName("b_conf_ayarla")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(250, 720, 51, 31))
        self.label_13.setObjectName("label_13")
        self.l_conf = QtWidgets.QLineEdit(self.centralwidget)
        self.l_conf.setGeometry(QtCore.QRect(240, 770, 61, 20))
        self.l_conf.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.l_conf.setObjectName("l_conf")
        self.l_arac = QtWidgets.QLabel(self.centralwidget)
        self.l_arac.setGeometry(QtCore.QRect(170, 430, 41, 31))
        self.l_arac.setObjectName("l_arac")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1490, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MERKUT_MGM"))
        self.b_start_kamera.setText(_translate("MainWindow", "Start Camera"))
        self.l_baglanti.setText(_translate("MainWindow", "Bağlantı Yok"))
        self.b_baglan.setText(_translate("MainWindow", "Bağlan"))
        self.b_baglanti_kes.setText(_translate("MainWindow", "Bağlantıyı kes"))
        self.b_armET.setText(_translate("MainWindow", "Arm et"))
        self.b_disarmET.setText(_translate("MainWindow", "Disarm et"))
        self.l_arm.setText(_translate("MainWindow", "Bilinmiyor"))
        self.b_modLOITER.setText(_translate("MainWindow", "Loiter"))
        self.b_modUYGULA.setText(_translate("MainWindow", "MOD Uygula"))
        self.comboBox.setItemText(0, _translate("MainWindow", "RTL"))
        self.comboBox.setItemText(1, _translate("MainWindow", "AUTO"))
        self.comboBox.setItemText(2, _translate("MainWindow", "FBWA"))
        self.comboBox.setItemText(3, _translate("MainWindow", "FBWB"))
        self.comboBox.setItemText(4, _translate("MainWindow", "STABILIZE"))
        self.comboBox.setItemText(5, _translate("MainWindow", "LOITER"))
        self.comboBox.setItemText(6, _translate("MainWindow", "TAKEOFF"))
        self.comboBox.setItemText(7, _translate("MainWindow", "MANUAL"))
        self.comboBox.setItemText(8, _translate("MainWindow", "GUIDED"))
        self.b_modRTL.setText(_translate("MainWindow", "RTL"))
        self.b_modAUTO.setText(_translate("MainWindow", "Auto"))
        self.b_modFBWA.setText(_translate("MainWindow", "FBWA"))
        self.pushButton_2.setText(_translate("MainWindow", "Guided"))
        self.label_3.setText(_translate("MainWindow", "Bağlantı-Arm"))
        self.label_4.setText(_translate("MainWindow", "Mod Seçimi"))
        self.b_solalt.setText(_translate("MainWindow", "solalt"))
        self.b_solust.setText(_translate("MainWindow", "solust"))
        self.b_sagust.setText(_translate("MainWindow", "sagust"))
        self.b_sagalt.setText(_translate("MainWindow", "sagalt"))
        self.b_takipBaslat.setText(_translate("MainWindow", "Takip Başlat"))
        self.b_takipDurdur.setText(_translate("MainWindow", "Takip Durdur"))
        self.pushButton.setText(_translate("MainWindow", "Komut indir"))
        self.label.setText(_translate("MainWindow", "Altitude:"))
        self.label_2.setText(_translate("MainWindow", "AirSpeed:"))
        self.label_6.setText(_translate("MainWindow", "GrndSpeed:"))
        self.label_7.setText(_translate("MainWindow", " Battery:"))
        self.label_8.setText(_translate("MainWindow", "Roll:"))
        self.label_9.setText(_translate("MainWindow", "Pitch:"))
        self.label_10.setText(_translate("MainWindow", "Yaw:"))
        self.b_stop_kamera.setText(_translate("MainWindow", "Stop Camera"))
        self.b_kamera_indir.setText(_translate("MainWindow", "Kamera indir"))
        self.b_kamera_kaldir.setText(_translate("MainWindow", "Kamera kaldır"))
        self.l_kamera_alt.setText(_translate("MainWindow", "1000"))
        self.l_kamera_ust.setText(_translate("MainWindow", "2000"))
        self.label_11.setText(_translate("MainWindow", "alt"))
        self.label_12.setText(_translate("MainWindow", "ust"))
        self.b_arac_degistir.setText(_translate("MainWindow", "ARAC DEGİSTİR"))
        self.b_conf_ayarla.setText(_translate("MainWindow", "conf ayarla"))
        self.label_13.setText(_translate("MainWindow", "ust"))
        self.l_conf.setText(_translate("MainWindow", "0.7"))
        self.l_arac.setText(_translate("MainWindow", "Kara"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
